# By default the service account by these functions will be the cloudfunction
# default service account agent

substitutions:
  _REGION: us-central1
  _PROJECT: medtax-ocr-prototype


steps:
  # Deploy first function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        "functions", "deploy", "documents-parser-function",
        "--gen2",
        "--entry-point", "trigger",
        "--runtime", "python311",
        "--trigger-event-filters", "type=google.cloud.storage.object.v1.finalized",
        "--trigger-event-filters", "bucket=run-sources-medtax-ocr-prototype-us-central1",
        "--region", "${_REGION}",
        "--project", "${_PROJECT}"
      ]

  # Deploy second function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        "functions", "deploy", "send-front-end",
        "--gen2",
        "--entry-point", "sendTrigger",
        "--runtime", "python311",
        "--source", "return",
        "--trigger-event-filters", "type=google.cloud.storage.object.v1.finalized",
        "--trigger-event-filters", "bucket=processed_output_bucket",
        "--region", "${_REGION}",
        "--project", "${_PROJECT}"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
