

""" THE NAMING OF COLLECTION AND DOCUMENTS TO BE WRITTEN IN FIRESTORE WILL
    BE HANDLED HERE

    NORMAL UPLOADS
    COLLECTION (UPLOADER'S ID) / DOCUMENT (FILENAME remove the prefix and -0_finalized.json) /

    FOR BATCH UPLOADS
    COLLECTION (UPLOADER'S ID "(BATCH)") / DOCUMENT (OPERATION ID) / COLLECTION (OPERATION INDEX) / DOCUMENT (FILENAME) /

"""